In [2]:
import numpy as np

Questions 1:

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [7]:
a = np.arange(2,50,3)
a

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

Questions 2:

Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [24]:
# Accepting two lists from user
l1 =[]
l2 =[]
for i in range(0,5):
    item = int(input())
    l1.append(item)
for i in range(0,5):
    item = int(input())
    l2.append(item)    
    
print(l1)    
print()
print(l2)

99
89
1
23
78
97
54
3
45
69
[99, 89, 1, 23, 78]

[97, 54, 3, 45, 69]


In [25]:
# Converting list into numpy array and Array concatenation
arr1 = np.array(l1)
arr2 = np.array(l2)
appended = np.concatenate([arr1,arr2])
print(appended)

[99 89  1 23 78 97 54  3 45 69]


In [27]:
# sorted array
print(np.sort(appended))

[ 1  3 23 45 54 69 78 89 97 99]


Questions 3:
    
Write a code snippet to find the dimensions of a ndarray and its size.

In [29]:
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
 
# Printing array dimensions
print("No. of dimensions: ", arr.ndim)
 
# Printing size of array
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


Questions 4:

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippetHint: np.newaxis , np.expand_dims

In [49]:
# using np.newaxis
arr1d = np.array([1,2,3,4,5])
arr2d = arr1d[:, np.newaxis]
print(arr2d)
print(type(arr2d))
arr2d.shape

[[1]
 [2]
 [3]
 [4]
 [5]]
<class 'numpy.ndarray'>


(5, 1)

In [72]:
# using np.expand_dims
arr1 = np.array([4, 5])
arr1.shape


(2,)

In [73]:
# using np.expand_dims (continuation..)
arr2 = np.expand_dims(arr1, axis=0)
print(arr2)
arr2.shape


[[4 5]]


(1, 2)

Questions 5:

Consider two square numpy arrays. Stack them vertically and horizontally.Hint: Use vstack(), hstack()

In [59]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[10,11,12],
                 [13,14,15],
                 [16,17,18]])

# Horitzontal Stack
print('Horizontal Stack:', np.hstack((arr1, arr2)))

# Vertical Stack
print('Vertical stack:', np.vstack((arr1, arr2)))


Horizontal Stack: [[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
Vertical stack: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


Questions 6:

How to get unique items and counts of unique items?

In [57]:
arr = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Initial array:")
print(arr)
unique_items, counts_items = np.unique(arr, return_counts=True)
print("Unique items and count of unique items:")
print(np.asarray((unique_items, counts_items)))

Initial array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Unique items and count of unique items:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
